config/routes.rb
Rails.application.routes.draw do
  resources :ideas

  root 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  
  def new
    @idea = Idea.new
  end

  def index
    @idea = Idea.new
    @ideas = Idea.all
  end

  def create
    @ideas = Idea.all
    @idea = Idea.new(idea_params)
    @idea.save
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @ideas = Idea.all
    @idea = Idea.find(params[:id])
    @idea.update_attributes(idea_params)
  end
 
  def destroy
    @idea = Idea.find(params[:id]) 
    @ideas = Idea.all
    @idea.destroy
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, as: :text %> <br>
  <%= f.label :description %>
  <%= f.text_field :description, as: :text %> <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/ideas/_idea.html.erb
<div class="idea">
  <div class="row" style="padding: 5px;">
    <p><%= idea.title %></p>
    <p><%= idea.description %></p>
  </div>
  <p>ID: <%= idea.id %></p>
  <div class="row">
    <span><%= link_to edit_idea_path(idea), remote: true do %>
      <button type="button" class="update-button">Update Idea</button>
    <% end %></span>
  <span><%= link_to idea, remote: true, method: :delete, data: { confirm: "Are you sure?" } do %>
      <button type="button" class="delete-button">Delete</button>
    <% end %></span>
  </div>
</div>

app/views/ideas/create.js.erb
$(".idea-list").html("<%= escape_javascript(render @ideas) %>");
$(".idea-form").slideUp(350);

app/views/ideas/destroy.js.erb
$(".idea-list").html("<%= escape_javascript(render @ideas) %>")

app/views/ideas/edit.js.erb
$(".idea-form").html("<%= escape_javascript(render 'form') %>");
$(".idea-form").slideDown(350);

app/views/ideas/index.html.erb
<div class="container">

  <div class="twelve columns">

    <div class="head-banner">
      <h2 style="align: center">Super IdeaBox</h2>

      <%= link_to new_idea_path, remote: true do %>
      <button type="button" class="new-idea-button">Create New Idea</button>
    <% end %>
    </div>

    <div class="row">
      <div class="row">
        <div class="five column idea-form hidden"></div>
      </div>

      <div class="five columns idea-list">
        <%= render @ideas %>
      </div>
    </div>

  </div>
</div>

app/views/ideas/new.js.erb
$(".idea-form").html("<%= escape_javascript(render 'form') %>");
$(".idea-form").slideDown(350);

app/views/ideas/update.js.erb
$(".idea-list").html("<%= escape_javascript(render @ideas) %>");
$(".idea-form").slideUp(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperIdeaBox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>